### ISSUE TITLE
Bypass pp/copy block

### ISSUE THREAD

**Issue by end360** [SnowboiTheGr8/gmod-anticrash#1]
It appears that setting the material override to `pp/adsf/../copy` rather than `pp/copy` still works, and bypasses your filter. Tested it in singleplayer and I could still use the toolgun.

**Comment by drizmans** [comment]
https://github.com/SnowboiTheGr8/gmod-anticrash/commit/f4bee29813b84156ec09c319da6406355f94f1ce

fixed
